apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.frontend.namespace }}
  labels:
    name: {{ .Values.frontend.namespace }}
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.backend.namespace }}
  labels:
    name: {{ .Values.backend.namespace }}
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}