apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: todoapp-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.todoapp.port }}
      protocol: TCP
      name: http
  selector:
    app: todoapp
